version: '3'
services:
  pypicloud:
    command: sh -c '/wait-for postgres:5432 -- uwsgi --die-on-term /etc/pypicloud/config.ini'
    depends_on:
      - postgres
    image: stevearc/pypicloud
    ports:
      - "8080:8080"
    volumes:
      - ./config-pg.ini:/etc/pypicloud/config.ini:ro
      - ./wait-for:/wait-for:ro
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
